### ISSUE TITLE
If-Match does not behave as it should.

### ISSUE THREAD

**Issue by mellester** [365Werk/etagconditionals#11]
According to the rfc If-match allows for a list of Etags, of which any one of them can be they correct Etag for  the request.
https://datatracker.ietf.org/doc/html/rfc2616#section-14.24

Also apparently '*' is the wildcard symbol and should be treated special .

**Comment by HergenD** [comment]
Ill adjust the if-match to work similar if-none-match comparison, where a list of etags is already supported.

I'll have a look at the wildcard too

Thanks for the issue

**Comment by HergenD** [comment]
Fixed in https://github.com/365Werk/etagconditionals/releases/tag/1.3.0
