### ISSUE TITLE
Handle "weak validators" – etags prepended with W/

### ISSUE THREAD

**Issue by bjuppa** [365Werk/etagconditionals#7]
Thanks for an excellent package, just what I needed, and super simple to use!
However, when I deployed to production where I have nginx configured to compress responses, I learned something new!

If a browser receives a __compressed__ `200` response, it seems to internally prepend `W/` to the etag string from the response headers, indicating a ["weak validator"](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag#directives). Then on subsequent requests that indicator is also sent to the server in the request header. It will look something like this: `If-None-Match: W/"cce76..."`

I think we can solve this by just stripping away any `W/` from the request etags, just before checking in the array: https://github.com/365Werk/etagconditionals/blob/aec728d177758e213e3a8d2d2928b3421f55c900/src/Middleware/IfNoneMatch.php#L33-L37

If you think this is the correct solution, I'm willing to do a PR!

Here's a short discussion for reference: https://stackoverflow.com/questions/51973120/where-does-the-w-in-an-etag-appear-from
...although they say nginx adds the indicator, but I'm pretty sure it's the browser that does it from testing with curl.

Example from my own production site (where I have werk365/etagconditionals installed): `curl -I  https://www.equaliteam.com/` will give you a clean etag, while inspecting the same url in a browser like Chrome you can see the `W/`

**Comment by HergenD** [comment]
Thanks @bjuppa 

You're right that we can safely remove the `W/` since the `If-None-Match` request allows us to use [a weak comparison algorithm](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match) which would result in the [desired result](https://tools.ietf.org/html/rfc7232#section-2.3.2).

Feel free to submit a PR for this.

I am curious if you would also have this issue with a `If-Match` request (if you're using those), because those have to be compared using [a string comparison algorithm](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Match)

**Comment by bjuppa** [comment]
Cool @HergenD, I'll see if I can whip up a PR tomorrow!

Interesting point there with `If-Match`, although I haven't tried using it myself yet... I would guess that when used with `GET` in a `Range` request, the strong comparison would be absolutely required.

But as the use case in this package is to prevent outdated `PATCH` requests to an API, strong comparison doesn't really make sense. The _meaning_ of that data should not be different due to any compression in transport, it's just a tag for the data, not for transport. So with `PATCH` it should also be safe to strip out `W/` before comparison, if the client added it to a compressed `GET`. What do you think?

**Comment by HergenD** [comment]
You're right that it should not matter for our use case. I think using a weak comparison would be fine in both the case of  `If-None-Match`  and `If-Match`. I think adding this behavior as default and then allowing an optional config entry to enable a strict comparison would be the best way to go about it.

**Comment by bjuppa** [comment]
I agree @HergenD, a config entry to enable strict comparison is a good idea.

 Now that this has grown from just stripping the `W/` in a single place, do you want to take over, or still want me to PR?

**Comment by HergenD** [comment]
I'll push this feature later today :)

**Comment by HergenD** [comment]
Thanks for the great issue @bjuppa 

The new feature is now up in 1.1.0

**Comment by bjuppa** [comment]
I've deployed your 1.1.0 version to production now, it works great! Thanks @HergenD !
